spring:
  application:
    name: foreign-word-chat
  http:
    converters:
      preferred-json-mapper: jackson2
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8888

logging:
  level:
    org:
      springframework: DEBUG
