package fi.publishertools.foreign.jobs;

public enum JobPhase {

	QUEUED_PHASE01_SPLIT,
	PHASE01_SPLITTING,
	QUEUED_LEGACY_POST_SPLIT,
	LEGACY_PROCESSING,

	QUEUED_WORDS4_PHASE02,
	WORDS4_PHASE02,
	QUEUED_WORDS4_PHASE03,
	WORDS4_PHASE03,
	QUEUED_WORDS4_PHASE04,
	WORDS4_PHASE04,

	COMPLETED,
	FAILED
}
